/* Insert data into Dhoma */

insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (16, 3, 29, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (20, 3, 29, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (1, 1, 9, 'Integer ac neque.');
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (5, 3, 24, 'Duis consequat dui nec nisi volutpat eleifend.');
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (14, 2, 25, 'Nulla ac enim.');
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (18, 3, 12, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (4, 2, 29, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (12, 1, 29, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (20, 2, 11, 'Curabitur convallis.');
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (11, 2, 7, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (5, 2, 25, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (17, 1, 17, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (6, 2, 6, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (13, 2, 21, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (17, 1, 4, 'Suspendisse potenti.');
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (2, 1, 6, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (3, 2, 11, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (16, 3, 28, 'Quisque id justo sit amet sapien dignissim vestibulum.');
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (20, 3, 13, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (5, 3, 12, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (2, 1, 30, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (1, 1, 16, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (20, 2, 7, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (5, 3, 9, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (16, 1, 7, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (6, 1, 10, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (10, 1, 7, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (15, 3, 21, 'Suspendisse accumsan tortor quis turpis.');
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (4, 3, 19, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (19, 3, 4, 'Morbi porttitor lorem id ligula.');
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (10, 3, 7, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (5, 3, 29, 'In hac habitasse platea dictumst.');
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (2, 2, 10, 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (16, 2, 25, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (11, 1, 20, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (17, 1, 24, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (5, 3, 9, 'Phasellus sit amet erat.');
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (12, 1, 13, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (1, 2, 11, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (17, 3, 20, 'Nunc purus.');
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (14, 1, 12, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (18, 2, 26, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (8, 3, 30, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (7, 2, 27, 'Nulla tellus.');
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (5, 3, 26, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (19, 3, 14, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (4, 3, 12, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (6, 3, 11, 'In congue.');
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (17, 1, 5, 'Suspendisse potenti.');
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (18, 3, 7, 'Vestibulum sed magna at nunc commodo placerat.');
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (6, 1, 21, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (13, 1, 24, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (10, 1, 1, 'Curabitur convallis.');
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (4, 3, 18, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (12, 3, 24, 'Quisque porta volutpat erat.');
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (6, 1, 22, 'Duis bibendum.');
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (7, 1, 4, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (11, 3, 12, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (20, 2, 21, 'Maecenas tincidunt lacus at velit.');
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (17, 3, 25, 'Aliquam sit amet diam in magna bibendum imperdiet.');
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (9, 3, 21, 'Donec dapibus.');
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (11, 2, 11, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (13, 1, 25, 'Etiam faucibus cursus urna.');
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (20, 1, 25, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (20, 1, 2, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (19, 1, 25, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (10, 3, 22, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (8, 2, 3, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (18, 2, 21, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (12, 3, 5, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (12, 3, 16, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (3, 2, 15, 'Donec posuere metus vitae ipsum.');
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (17, 2, 8, 'In hac habitasse platea dictumst.');
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (7, 2, 3, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (7, 3, 8, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (6, 1, 6, 'Morbi a ipsum.');
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (4, 3, 10, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (12, 2, 30, 'Nulla facilisi.');
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (6, 2, 19, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (18, 3, 21, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (6, 1, 7, 'In hac habitasse platea dictumst.');
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (7, 1, 10, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (9, 2, 15, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (20, 1, 21, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (5, 3, 2, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (4, 1, 2, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (15, 1, 24, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (2, 3, 29, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (10, 3, 28, null);
insert into dbo.Dhoma (TipDhomeId, CmimDhomeId, Kat, Shenime) values (11, 2, 10, 'Nam dui.');

select * from dbo.Dhoma;
