/* Insert data into Paisje */

insert into dbo.Paisje (PaisjePershkrim) values ('Sed sagittis.');
insert into dbo.Paisje (PaisjePershkrim) values ('Mauris ullamcorper purus sit amet nulla.');
insert into dbo.Paisje (PaisjePershkrim) values ('Quisque id justo sit amet sapien dignissim vestibulum.');
insert into dbo.Paisje (PaisjePershkrim) values ('In hac habitasse platea dictumst.');
insert into dbo.Paisje (PaisjePershkrim) values ('Phasellus in felis.');
insert into dbo.Paisje (PaisjePershkrim) values ('Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into dbo.Paisje (PaisjePershkrim) values ('Mauris sit amet eros.');
insert into dbo.Paisje (PaisjePershkrim) values ('Aliquam sit amet diam in magna bibendum imperdiet.');
insert into dbo.Paisje (PaisjePershkrim) values ('Etiam faucibus cursus urna.');
insert into dbo.Paisje (PaisjePershkrim) values ('Nulla suscipit ligula in lacus.');
insert into dbo.Paisje (PaisjePershkrim) values ('Curabitur gravida nisi at nibh.');
insert into dbo.Paisje (PaisjePershkrim) values ('Suspendisse potenti.');
insert into dbo.Paisje (PaisjePershkrim) values ('Praesent blandit.');
insert into dbo.Paisje (PaisjePershkrim) values ('Pellentesque ultrices mattis odio.');
insert into dbo.Paisje (PaisjePershkrim) values ('Duis at velit eu est congue elementum.');
insert into dbo.Paisje (PaisjePershkrim) values ('Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
insert into dbo.Paisje (PaisjePershkrim) values ('In congue.');
insert into dbo.Paisje (PaisjePershkrim) values ('Pellentesque viverra pede ac diam.');
insert into dbo.Paisje (PaisjePershkrim) values ('Donec dapibus.');
insert into dbo.Paisje (PaisjePershkrim) values ('Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into dbo.Paisje (PaisjePershkrim) values ('Etiam pretium iaculis justo.');
insert into dbo.Paisje (PaisjePershkrim) values ('Mauris ullamcorper purus sit amet nulla.');
insert into dbo.Paisje (PaisjePershkrim) values ('Nunc purus.');
insert into dbo.Paisje (PaisjePershkrim) values ('Sed vel enim sit amet nunc viverra dapibus.');
insert into dbo.Paisje (PaisjePershkrim) values ('Proin interdum mauris non ligula pellentesque ultrices.');
insert into dbo.Paisje (PaisjePershkrim) values ('Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into dbo.Paisje (PaisjePershkrim) values ('Nam nulla.');
insert into dbo.Paisje (PaisjePershkrim) values ('Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into dbo.Paisje (PaisjePershkrim) values ('Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into dbo.Paisje (PaisjePershkrim) values ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into dbo.Paisje (PaisjePershkrim) values ('Duis ac nibh.');
insert into dbo.Paisje (PaisjePershkrim) values ('Curabitur convallis.');
insert into dbo.Paisje (PaisjePershkrim) values ('Duis at velit eu est congue elementum.');
insert into dbo.Paisje (PaisjePershkrim) values ('Sed vel enim sit amet nunc viverra dapibus.');
insert into dbo.Paisje (PaisjePershkrim) values ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into dbo.Paisje (PaisjePershkrim) values ('Nullam varius.');
insert into dbo.Paisje (PaisjePershkrim) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into dbo.Paisje (PaisjePershkrim) values ('Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into dbo.Paisje (PaisjePershkrim) values ('Nulla mollis molestie lorem.');
insert into dbo.Paisje (PaisjePershkrim) values ('Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into dbo.Paisje (PaisjePershkrim) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into dbo.Paisje (PaisjePershkrim) values ('Nulla justo.');
insert into dbo.Paisje (PaisjePershkrim) values ('Nulla tellus.');
insert into dbo.Paisje (PaisjePershkrim) values ('Phasellus id sapien in sapien iaculis congue.');
insert into dbo.Paisje (PaisjePershkrim) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into dbo.Paisje (PaisjePershkrim) values ('Pellentesque eget nunc.');
insert into dbo.Paisje (PaisjePershkrim) values ('In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into dbo.Paisje (PaisjePershkrim) values ('Etiam vel augue.');
insert into dbo.Paisje (PaisjePershkrim) values ('Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into dbo.Paisje (PaisjePershkrim) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into dbo.Paisje (PaisjePershkrim) values ('Mauris ullamcorper purus sit amet nulla.');
insert into dbo.Paisje (PaisjePershkrim) values ('Phasellus sit amet erat.');
insert into dbo.Paisje (PaisjePershkrim) values ('Nulla tellus.');
insert into dbo.Paisje (PaisjePershkrim) values ('In blandit ultrices enim.');
insert into dbo.Paisje (PaisjePershkrim) values ('Suspendisse accumsan tortor quis turpis.');
insert into dbo.Paisje (PaisjePershkrim) values ('Nunc purus.');
insert into dbo.Paisje (PaisjePershkrim) values ('Cras in purus eu magna vulputate luctus.');
insert into dbo.Paisje (PaisjePershkrim) values ('Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into dbo.Paisje (PaisjePershkrim) values ('Nulla tempus.');
insert into dbo.Paisje (PaisjePershkrim) values ('Integer ac neque.');
insert into dbo.Paisje (PaisjePershkrim) values ('Nunc nisl.');
insert into dbo.Paisje (PaisjePershkrim) values ('Nulla facilisi.');
insert into dbo.Paisje (PaisjePershkrim) values ('Vivamus vel nulla eget eros elementum pellentesque.');
insert into dbo.Paisje (PaisjePershkrim) values ('In sagittis dui vel nisl.');
insert into dbo.Paisje (PaisjePershkrim) values ('Pellentesque at nulla.');
insert into dbo.Paisje (PaisjePershkrim) values ('Integer ac neque.');
insert into dbo.Paisje (PaisjePershkrim) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into dbo.Paisje (PaisjePershkrim) values ('Ut tellus.');
insert into dbo.Paisje (PaisjePershkrim) values ('Nulla mollis molestie lorem.');
insert into dbo.Paisje (PaisjePershkrim) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into dbo.Paisje (PaisjePershkrim) values ('Mauris ullamcorper purus sit amet nulla.');
insert into dbo.Paisje (PaisjePershkrim) values ('Pellentesque ultrices mattis odio.');
insert into dbo.Paisje (PaisjePershkrim) values ('Nullam porttitor lacus at turpis.');
insert into dbo.Paisje (PaisjePershkrim) values ('In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into dbo.Paisje (PaisjePershkrim) values ('Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into dbo.Paisje (PaisjePershkrim) values ('Praesent blandit lacinia erat.');
insert into dbo.Paisje (PaisjePershkrim) values ('Morbi porttitor lorem id ligula.');
insert into dbo.Paisje (PaisjePershkrim) values ('Curabitur at ipsum ac tellus semper interdum.');
insert into dbo.Paisje (PaisjePershkrim) values ('Proin eu mi.');
insert into dbo.Paisje (PaisjePershkrim) values ('Praesent blandit lacinia erat.');
insert into dbo.Paisje (PaisjePershkrim) values ('Nullam porttitor lacus at turpis.');
insert into dbo.Paisje (PaisjePershkrim) values ('Nulla justo.');
insert into dbo.Paisje (PaisjePershkrim) values ('Curabitur in libero ut massa volutpat convallis.');
insert into dbo.Paisje (PaisjePershkrim) values ('Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into dbo.Paisje (PaisjePershkrim) values ('Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into dbo.Paisje (PaisjePershkrim) values ('Integer ac leo.');
insert into dbo.Paisje (PaisjePershkrim) values ('Praesent lectus.');
insert into dbo.Paisje (PaisjePershkrim) values ('Suspendisse potenti.');
insert into dbo.Paisje (PaisjePershkrim) values ('Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into dbo.Paisje (PaisjePershkrim) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into dbo.Paisje (PaisjePershkrim) values ('Integer ac leo.');
insert into dbo.Paisje (PaisjePershkrim) values ('Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into dbo.Paisje (PaisjePershkrim) values ('Vestibulum rutrum rutrum neque.');
insert into dbo.Paisje (PaisjePershkrim) values ('Curabitur gravida nisi at nibh.');
insert into dbo.Paisje (PaisjePershkrim) values ('Pellentesque ultrices mattis odio.');
insert into dbo.Paisje (PaisjePershkrim) values ('Nulla nisl.');
insert into dbo.Paisje (PaisjePershkrim) values ('Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into dbo.Paisje (PaisjePershkrim) values ('Maecenas rhoncus aliquam lacus.');
insert into dbo.Paisje (PaisjePershkrim) values ('Mauris sit amet eros.');
insert into dbo.Paisje (PaisjePershkrim) values ('Sed accumsan felis.');

select * from dbo.Paisje;
