/* Insert data into PaisjeDhome */

insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (8, 55, 'odio condimentum id luctus nec');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (7, 96, 'molestie nibh in lectus pellentesque');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (31, 52, 'ipsum primis in');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (5, 52, 'suspendisse potenti in eleifend quam');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (78, 54, 'morbi vel lectus');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (50, 9, 'accumsan odio curabitur convallis duis');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (18, 2, 'condimentum id luctus nec');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (90, 13, 'eget nunc donec');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (85, 52, 'non mattis pulvinar nulla pede');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (51, 83, 'commodo placerat praesent blandit');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (90, 90, 'eget orci vehicula');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (49, 17, 'tincidunt ante vel ipsum praesent');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (22, 61, 'lobortis sapien sapien non mi');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (22, 27, 'nullam varius nulla');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (20, 81, 'lacus at velit vivamus');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (81, 32, 'et ultrices posuere cubilia curae');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (79, 59, 'velit donec diam neque vestibulum');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (90, 5, 'nunc proin at turpis');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (19, 28, 'at ipsum ac tellus semper');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (90, 95, 'orci luctus et ultrices');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (42, 10, 'primis in faucibus orci luctus');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (61, 36, 'ut mauris eget massa');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (86, 74, 'adipiscing molestie hendrerit at');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (62, 64, 'nulla sed vel');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (7, 62, 'dolor vel est donec odio');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (61, 70, 'libero quis orci');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (17, 62, 'vulputate luctus cum sociis natoque');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (90, 48, 'magna ac consequat metus');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (26, 87, 'pellentesque quisque porta volutpat erat');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (34, 82, 'malesuada in imperdiet et commodo');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (90, 31, 'porta volutpat erat');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (62, 15, 'in lectus pellentesque at nulla');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (50, 91, 'amet cursus id');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (56, 43, 'pede ullamcorper augue a suscipit');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (4, 59, 'felis sed lacus morbi');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (90, 87, 'id sapien in sapien');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (19, 58, 'proin leo odio porttitor id');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (64, 67, 'semper rutrum nulla nunc purus');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (56, 64, 'dictumst aliquam augue quam');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (50, 87, 'turpis donec posuere metus vitae');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (63, 6, 'porttitor id consequat in');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (29, 81, 'felis eu sapien cursus');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (79, 9, 'molestie sed justo pellentesque viverra');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (51, 49, 'in hac habitasse');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (65, 20, 'sit amet consectetuer');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (68, 16, 'malesuada in imperdiet');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (42, 98, 'volutpat quam pede');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (70, 11, 'ut erat id mauris');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (8, 9, 'turpis elementum ligula vehicula');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (89, 23, 'erat tortor sollicitudin');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (70, 61, 'massa volutpat convallis morbi odio');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (41, 51, 'nullam porttitor lacus');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (35, 95, 'ipsum integer a nibh');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (51, 50, 'massa quis augue luctus tincidunt');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (20, 83, 'tincidunt eu felis');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (52, 96, 'dapibus augue vel');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (21, 71, 'consequat ut nulla');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (76, 87, 'ultrices phasellus id');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (84, 14, 'magna ac consequat metus sapien');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (14, 25, 'consequat nulla nisl');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (90, 38, 'nunc nisl duis bibendum');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (39, 11, 'lorem quisque ut erat');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (48, 8, 'aenean lectus pellentesque eget nunc');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (16, 44, 'neque vestibulum eget vulputate');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (65, 2, 'et tempus semper est quam');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (51, 48, 'nulla ut erat');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (2, 18, 'tortor eu pede');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (40, 18, 'accumsan odio curabitur convallis duis');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (90, 68, 'tellus nulla ut');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (88, 87, 'volutpat in congue');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (16, 95, 'ac nibh fusce lacus');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (58, 33, 'id turpis integer aliquet massa');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (54, 38, 'justo sollicitudin ut suscipit a');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (1, 92, 'non mattis pulvinar nulla');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (43, 12, 'ligula sit amet eleifend');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (82, 95, 'maecenas ut massa quis');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (90, 4, 'ultrices libero non mattis');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (60, 90, 'ultrices posuere cubilia curae');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (23, 73, 'penatibus et magnis dis parturient');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (16, 1, 'ipsum primis in faucibus');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (69, 53, 'congue elementum in');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (89, 65, 'eleifend pede libero');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (83, 50, 'rutrum nulla nunc');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (10, 5, 'est risus auctor sed');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (90, 70, 'interdum venenatis turpis enim blandit');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (11, 88, 'rhoncus mauris enim leo');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (65, 51, 'quis augue luctus');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (42, 26, 'odio condimentum id luctus nec');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (90, 7, 'suscipit ligula in');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (35, 45, 'sodales scelerisque mauris sit');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (58, 71, 'vehicula consequat morbi a ipsum');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (12, 89, 'ante nulla justo aliquam');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (49, 29, 'faucibus cursus urna');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (49, 15, 'convallis duis consequat');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (54, 87, 'duis bibendum felis sed interdum');
insert into dbo.PaisjeDhome (DhomaId, PaisjeId, Detaje) values (86, 53, 'ultrices mattis odio donec vitae');

select * from dbo.PaisjeDhome;
